name: parc
description: A smart parking system.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  flutter_bloc: ^2.0.0
  equatable: ^1.0.0
  google_maps_flutter: 0.5.15+1
  geolocator: ^5.1.5
  provider: ^3.2.0
  location: ^2.3.5
  url_launcher: ^5.2.7

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
